# Generated by Django 3.0.6 on 2020-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib_api', '0002_auto_20160907_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciresults',
            name='result',
            field=models.CharField(max_length=4000),
        ),
    ]
